"use client";

import { AlertTriangle, CheckCircle2, ExternalLink, Info, X } from "lucide-react";
import type { ReactNode } from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import type { DataSourceRecord } from "@/lib/types";

export function DataHealthDrawer({
  open,
  sources,
  onClose,
}: {
  open: boolean;
  sources: DataSourceRecord[];
  onClose: () => void;
}) {
  if (!open) return null;

  const liveSources = sources.filter((source) => source.health_status === "healthy");
  const fallbackActive = sources.some((source) => source.health_status !== "healthy");
  const optionalApiFootballPresent = false;

  return (
    <div className="fixed inset-0 z-50 bg-slate-950/55 backdrop-blur-sm">
      <div className="flex h-full items-stretch justify-end">
        <Card className="flex h-full w-full max-w-xl flex-col rounded-none border-l border-slate-200 bg-white shadow-[0_28px_90px_rgba(15,23,42,0.32)]">
          <CardHeader className="border-b border-slate-200 bg-slate-50/90">
            <div className="flex items-start justify-between gap-3">
              <div>
                <p className="text-xs font-semibold uppercase tracking-[0.22em] text-slate-500">Data health</p>
                <CardTitle className="mt-1 text-2xl font-black text-slate-950">Where the app gets its data</CardTitle>
              </div>
              <Button
                variant="ghost"
                size="sm"
                className="h-9 w-9 px-0"
                onClick={onClose}
                aria-label="Close data health drawer"
              >
                <X className="h-4 w-4" />
              </Button>
            </div>
          </CardHeader>
          <CardContent className="flex-1 space-y-4 overflow-y-auto p-5">
            <div className="grid gap-3 sm:grid-cols-2">
              <InfoTile
                label="Live/free-source data"
                tone="success"
                icon={<CheckCircle2 className="h-4 w-4" />}
                description="Values pulled from free APIs when the source is available and healthy."
              />
              <InfoTile
                label="Curated fallback data"
                tone={fallbackActive ? "warning" : "muted"}
                icon={<AlertTriangle className="h-4 w-4" />}
                description="Manually researched Bayern fallback data used only for gameplay continuity."
              />
              <InfoTile
                label="Simulator estimate"
                tone="gold"
                icon={<Info className="h-4 w-4" />}
                description="App-generated values, ratings, or projections. Not official market data."
              />
              <InfoTile
                label="Simulator model"
                tone="muted"
                icon={<Info className="h-4 w-4" />}
                description="Internal model output used for fit, confidence, and projections."
              />
            </div>

            <div className="rounded-2xl border border-slate-200 bg-slate-50 p-4">
              <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
                <p className="text-xs font-semibold uppercase tracking-[0.18em] text-slate-500">Source list</p>
                <div className="flex flex-wrap gap-2">
                  <Badge tone={liveSources.length ? "success" : "muted"}>{liveSources.length} live</Badge>
                  <Badge tone={fallbackActive ? "warning" : "success"}>{fallbackActive ? "fallback active" : "all healthy"}</Badge>
                </div>
              </div>

              <div className="mt-3 space-y-2">
                {sources.map((source) => (
                  <SourceRow key={source.id} source={source} />
                ))}

                <SpecialSourceRow
                  label="API-Football"
                  tone="muted"
                  description="Optional external source. Not required for the MVP and safe to leave disabled."
                  enabled={optionalApiFootballPresent}
                  status={optionalApiFootballPresent ? "enabled" : "disabled"}
                />
                <SpecialSourceRow
                  label="Curated fallback / manual research"
                  tone={fallbackActive ? "warning" : "muted"}
                  description="Manual research fallback used only when live sources are missing or incomplete."
                  enabled={fallbackActive}
                  status={fallbackActive ? "active" : "standby"}
                />
                <SpecialSourceRow
                  label="Simulator estimates / model layer"
                  tone="gold"
                  description="Generated by the app itself for fees, fit, confidence, and season projections."
                  enabled
                  status="active"
                />
              </div>
            </div>

            <div className="rounded-2xl border border-slate-200 bg-white p-4">
              <p className="text-xs font-semibold uppercase tracking-[0.18em] text-slate-500">What the labels mean</p>
              <ul className="mt-3 space-y-2 text-sm leading-6 text-slate-700">
                <li className="rounded-xl border border-slate-200 bg-slate-50 px-3 py-2">
                  <strong>Live/free-source data</strong> means a value came from a free API source that is currently healthy.
                </li>
                <li className="rounded-xl border border-slate-200 bg-slate-50 px-3 py-2">
                  <strong>Curated fallback data</strong> means a manually researched Bayern baseline used for continuity.
                </li>
                <li className="rounded-xl border border-slate-200 bg-slate-50 px-3 py-2">
                  <strong>Manual research fallback</strong> is not live data and should never be presented as official.
                </li>
                <li className="rounded-xl border border-slate-200 bg-slate-50 px-3 py-2">
                  <strong>Simulator estimate</strong> means the app generated the number itself, not the market.
                </li>
                <li className="rounded-xl border border-slate-200 bg-slate-50 px-3 py-2">
                  <strong>Estimated wage tier</strong> is a wage band estimate, not an official salary figure.
                </li>
                <li className="rounded-xl border border-slate-200 bg-slate-50 px-3 py-2">
                  Missing API keys or disabled sources do not crash the app. They fall back safely instead.
                </li>
              </ul>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}

function SourceRow({ source }: { source: DataSourceRecord }) {
  const tone =
    source.health_status === "healthy"
      ? "success"
      : source.health_status === "degraded"
        ? "gold"
        : source.health_status === "disabled"
          ? "muted"
          : "warning";

  return (
    <div className="flex flex-col gap-2 rounded-2xl border border-slate-200 bg-white p-3 sm:flex-row sm:items-start sm:justify-between">
      <div className="min-w-0 space-y-1">
        <div className="flex flex-wrap items-center gap-2">
          <p className="font-semibold text-slate-950">{source.source_name}</p>
          <Badge tone={tone}>{source.health_status}</Badge>
          <Badge tone={source.enabled ? "success" : "muted"}>{source.enabled ? "enabled" : "disabled"}</Badge>
        </div>
        <p className="text-xs text-slate-500">{source.license_or_terms_note}</p>
        <p className="text-xs text-slate-600">
          <strong>Used for:</strong> {sourceUsage(source.source_name)}
        </p>
        {source.error_message ? <p className="text-xs text-red-600">{source.error_message}</p> : null}
      </div>
      <div className="flex flex-wrap items-center gap-2 text-xs text-slate-500">
        <span>{lastCheckedLabel(source.last_checked_at)}</span>
        {source.source_url ? (
          <a
            href={source.source_url}
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center gap-1 rounded-full border border-slate-200 bg-slate-50 px-2 py-1 transition-colors hover:border-[#b80d19]/30 hover:text-[#b80d19]"
          >
            Source
            <ExternalLink className="h-3 w-3" />
          </a>
        ) : null}
      </div>
    </div>
  );
}

function SpecialSourceRow({
  label,
  description,
  enabled,
  status,
  tone,
}: {
  label: string;
  description: string;
  enabled: boolean;
  status: string;
  tone: "success" | "warning" | "gold" | "muted";
}) {
  return (
    <div className="flex flex-col gap-2 rounded-2xl border border-dashed border-slate-300 bg-white p-3 sm:flex-row sm:items-start sm:justify-between">
      <div className="min-w-0 space-y-1">
        <div className="flex flex-wrap items-center gap-2">
          <p className="font-semibold text-slate-950">{label}</p>
          <Badge tone={tone}>{status}</Badge>
          <Badge tone={enabled ? "success" : "muted"}>{enabled ? "enabled" : "disabled"}</Badge>
        </div>
        <p className="text-xs text-slate-600">{description}</p>
      </div>
    </div>
  );
}

function InfoTile({
  label,
  description,
  tone,
  icon,
}: {
  label: string;
  description: string;
  tone: "success" | "warning" | "gold" | "muted";
  icon: ReactNode;
}) {
  return (
    <div className="rounded-2xl border border-slate-200 bg-white p-4">
      <div className="flex items-center gap-2">
        <Badge tone={tone} className="flex items-center gap-1">
          {icon}
          {label}
        </Badge>
      </div>
      <p className="mt-3 text-sm leading-6 text-slate-600">{description}</p>
    </div>
  );
}

function lastCheckedLabel(value: string | null) {
  if (!value) return "Never checked";
  const diff = Date.now() - new Date(value).getTime();
  const hours = diff / 1000 / 60 / 60;
  if (hours < 1) return "Just checked";
  if (hours < 24) return `${Math.round(hours)}h ago`;
  const days = Math.floor(hours / 24);
  return `${days}d ago`;
}

function sourceUsage(sourceName: string) {
  if (sourceName === "openligadb") return "League fixtures, results, and standings";
  if (sourceName === "football-data") return "Club and competition reference data";
  if (sourceName === "wikidata") return "Identity, club, and player metadata";
  if (sourceName === "thesportsdb") return "Broad sports reference coverage";
  if (sourceName === "api-football") return "Optional enrichment if configured";
  return "General source support";
}
